# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-01-04 13:15
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contact',
            name='qwirkUser',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='project.QwirkUser'),
        ),
    ]
