# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-01-02 14:18
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='qwirkuser',
            name='bio',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='qwirkuser',
            name='birthDate',
            field=models.DateField(null=True),
        ),
    ]
