# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-01-03 13:41
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0003_qwirkuser_contacts'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='qwirkuser',
            name='contacts',
        ),
        migrations.AddField(
            model_name='qwirkuser',
            name='contacts',
            field=models.ManyToManyField(null=True, related_name='_qwirkuser_contacts_+', to='project.QwirkUser'),
        ),
    ]
