# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-06 16:42
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0003_auto_20170306_1722'),
    ]

    operations = [
        migrations.RenameField(
            model_name='qwirkuser',
            old_name='groups',
            new_name='qwirkGroups',
        ),
    ]
