# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-01-03 13:46
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0008_alter_user_username_max_length'),
        ('project', '0004_auto_20170103_1441'),
    ]

    operations = [
        migrations.AddField(
            model_name='qwirkuser',
            name='groups',
            field=models.ManyToManyField(null=True, to='auth.Group'),
        ),
    ]
