# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-08 10:20
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0004_auto_20170306_1742'),
    ]

    operations = [
        migrations.RenameField(
            model_name='qwirkgroup',
            old_name='private',
            new_name='isPrivate',
        ),
    ]
