# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-05-04 13:27
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0006_notification'),
    ]

    operations = [
        migrations.AddField(
            model_name='notification',
            name='dateRead',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='notification',
            name='dateWrite',
            field=models.DateTimeField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='notification',
            name='message',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='project.Message'),
        ),
        migrations.AlterField(
            model_name='notification',
            name='qwirkUser',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to='project.QwirkUser'),
        ),
    ]
