# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-05-04 13:33
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0007_auto_20170504_1527'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='notification',
            name='dateWrite',
        ),
    ]
