# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-05-04 15:17
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0008_remove_notification_datewrite'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='message',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='project.Message'),
        ),
    ]
