# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-05-22 13:10
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0010_message_type'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='qwirkgroup',
            name='admin',
        ),
        migrations.AddField(
            model_name='qwirkgroup',
            name='admins',
            field=models.ManyToManyField(related_name='admins', to='project.QwirkUser'),
        ),
        migrations.AddField(
            model_name='qwirkgroup',
            name='blockedUsers',
            field=models.ManyToManyField(related_name='blockedUsers', to='project.QwirkUser'),
        ),
    ]
