# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-05-22 13:12
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0011_auto_20170522_1310'),
    ]

    operations = [
        migrations.AlterField(
            model_name='qwirkgroup',
            name='blockedUsers',
            field=models.ManyToManyField(blank=True, related_name='blockedUsers', to='project.QwirkUser'),
        ),
    ]
