# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-05-24 13:10
from __future__ import unicode_literals

import django.core.files.storage
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0012_auto_20170522_1312'),
    ]

    operations = [
        migrations.AddField(
            model_name='qwirkuser',
            name='avatar',
            field=models.ImageField(blank=True, null=True, storage=django.core.files.storage.FileSystemStorage(location='/home/adrien/git/4PJT/server'), upload_to=''),
        ),
    ]
